# Generated by Django 6.1 on 2026-08-16 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caterer_name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('Catering_minguest', models.IntegerField(default=1)),
                ('Catering_maxguest', models.IntegerField(default=2)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DJname', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VenueListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Venue_minguest', models.PositiveIntegerField(default=1)),
                ('Venue_maxguest', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('base_price', models.IntegerField()),
                ('services', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('dj', 'DJ')], max_length=20)),
                ('description', models.TextField()),
                ('pricing_model', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=15)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
