# Generated by Django 6.1 on 2026-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_vendorprofile_updated_at_vendorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_avatars/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Business Description', null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
